### ISSUE TITLE
it keeps crashing right after opening it up in windows

### ISSUE THREAD

**Issue by m-moein98** [opeolluwa/filesync#367]

**Comment by opeolluwa** [comment]
Is there any error message

**Comment by m-moein98** [comment]
no it just opens and immediately closes

**Comment by m-moein98** [comment]
tried multiple different versions including the latest

**Comment by opeolluwa** [comment]
The pre built binary?

**Comment by opeolluwa** [comment]
Or in the development mode

**Comment by m-moein98** [comment]
so far tried 7.7, 7.6, 7.5 from project's release page

**Comment by m-moein98** [comment]
https://github.com/user-attachments/assets/6a628066-8cbd-4990-84e5-2aa49956ae53

**Comment by m-moein98** [comment]
the recording is for this version
https://github.com/opeolluwa/filesync/releases/tag/app-v0.7.7

**Comment by opeolluwa** [comment]
I added a feature to close the application if it is not connected to a wifi 
I'm going to rework that

**Comment by opeolluwa** [comment]
alright thanks.
