### ISSUE TITLE
 Implement a feature that let users open/play audio files in the user interface.

### ISSUE THREAD

**Issue by opeolluwa** [opeolluwa/filesync#61]
The application core built with Rust fetches the audio files from the device's
 default audio directory and passes an array of these files to the UI for rendering. Implement a feature that let users open/play audio files in the user interface. 

See [convertFileSrc](https://tauri.app/fr/v1/api/js/tauri/#convertfilesrc) to get started and the music data structure [defined here ](https://github.com/opeolluwa/send-file/blob/master/core/src/commands/audio.rs#L14)

Experience with Rust Typescript,[ React/Next.js](https://nextjs.org/) and [Tauri ](https://tauri.app/) is required

**Comment by cardotrejos** [comment]
I would try to get more familiarized with the project, but this seems to be a good first issue to work in.

**Comment by opeolluwa** [comment]
Hi @cardotrejos, thanks for picking interest in what I'm building, I'm here to answer the questions you might have

**Comment by opeolluwa** [comment]
Hi @cardotrejos how's it going

**Comment by KenCox94** [comment]
> Hi @cardotrejos how's it going 

If @cardotrejos is not up for this issue anymore, would love to tackle it

**Comment by cardotrejos** [comment]
@opeolluwa I appreciate your patience with this! I would like to work on it.

**Comment by opeolluwa** [comment]
All right, @cardotrejos 
Here is what the functional requirement.

Create a reusable component, this can be implemented as a draggable element or an element fixed to the bottom of the application window.

There can only be one instance of the component at a time and it Will be used along with the Tauri [convertFileScr](https://tauri.app/fr/v1/api/js/tauri/#convertfilesrc) to play the audio. 

Not that, every audio file path already returns the file absolute path. 

You might have a lot of questions regards this, I'd be happy to answer and review this approach
